services:
  one:
    image: tugboatqa/debian
    default: true
    commands:
      build:
        - date
        - sleep 10
      online:
        - echo "$(hostname) start $(date)"
        - sleep 5
        - echo "$(hostname) end $(date)"
        - false
  two:
    image: tugboatqa/debian
    checkout: true
    commands:
      build:
        - date
      online:
        - echo "$(hostname) start $(date)"
        - sleep 1
        - echo "$(hostname) end $(date)"
      ready: test ! -f /var/lib/tugboat/.tugboat/config.yml || sleep 10
  three:
    image: tugboatqa/debian
    commands:
      build:
        - date
        - sleep 20
      online:
        - echo "$(hostname) start $(date)"
        - sleep 20
        - echo "$(hostname) end $(date)"
  four:
    image: tugboatqa/debian
    depends:
      - one
    commands:
      build:
        - date
        - sleep 25
      online:
        - echo "$(hostname) start $(date)"
        - sleep 10
        - echo "$(hostname) end $(date)"
