services:
  lighthouse:
    image: 'tugboatqa/node:12'
    checkout: true
    expose: 8080
    commands:
      init:
        - 'npm install -g @lhci/cli@0.4.x'
#        - 'npm install --prefix=${TUGBOAT_ROOT}/tests/lighthouse'
#        - 'mkdir -p /etc/service/node'
#        - 'echo ''#!/bin/sh'' > /etc/service/node/run'
#        - 'echo "node ${TUGBOAT_ROOT}/tests/lighthouse" >> /etc/service/node/run'
#        - 'chmod +x /etc/service/node/run'
#      build:
#        - 'tests/lighthouse/test.sh || true'
