services:
  solr:
    image: tugboatqa/solr:9.7
    default: true
    expose: 8983
    commands:
      init:
        # Set up basic auth for solr admin.
        - sed -i "/\$rootScope.exceptions = {};/a \$scope.username = 'solr'; \$scope.password = 'SolrRocks';" /opt/solr/server/solr-webapp/webapp/js/angular/controllers/login.js
        # Stop solr.
        - sv stop solr
        # Now start solr with cloud mode as the solr user.
        - su -s /bin/sh -c "docker-entrypoint.sh solr start -c -Dlog4j.configurationFile=/opt/solr/server/resources/log4j2-console.xml" solr
        # Copy security.json into place.
        - solr zk cp file:"$TUGBOAT_ROOT"/.tugboat/solr/security.json zk:/security.json -z localhost:9983
        # Copy solr config with ZooKeeper to the config named solr.
        - solr zk upconfig -n "solr" -d "$TUGBOAT_ROOT"/.tugboat/solr/config -z localhost:9983
        # Create a SolrCloud collection named solr using the solr user.
        - su -s /bin/sh -c "/opt/solr/bin/solr create -c solr -n solr -d "$TUGBOAT_ROOT"/.tugboat/solr/config shards 1 -replicationFactor 1" solr
        # Stop our temporary solr server.
        - docker-entrypoint.sh solr stop
        # Modify the runit script to add -c to the solr-foreground command to
        # start in cloud mode.
        - sed -i 's/solr-foreground/& -c/' /etc/service/solr/run
        - sv start solr
