services:
  one:
    image: tugboatqa/debian
    default: true
    commands:
      build:
        - date
        - sleep 10
      online:
        - |
            expires=$(date --date="+1 hour" -u +"%Y-%m-%dT%H:%M:%SZ")
            curl -H "Authorization: Bearer ${TUGBOAT_ACCESS_TOKEN}" \
              -H "Content-Type: application/json" \
              -X PATCH -d "{ \"expires\": \"${expires}\" }" \
              https://api.tugboat.qa/v3/previews/${TUGBOAT_PREVIEW_ID}
