services:
  one:
    image: tugboatqa/debian
    default: true
    commands:
      online:
        - echo "$(hostname) start $(date)"
        - sleep 5
        - echo "$(hostname) end $(date)"
        - exit 23
  two:
    image: tugboatqa/debian
    commands:
      online:
        - echo "$(hostname) start $(date)"
        - sleep 1
        - echo "$(hostname) end $(date)"
  three:
    image: tugboatqa/debian
    commands:
      online:
        - echo "$(hostname) start $(date)"
        - sleep 20
        - echo "$(hostname) end $(date)"
        - false
  four:
    image: tugboatqa/debian
    depends:
      - one
    commands:
      online:
        - echo "$(hostname) start $(date)"
        - sleep 10
        - echo "$(hostname) end $(date)"
