services:
  one:
    image: tugboatqa/debian
    default: true
    commands:
      update:
        - rm -f $TUGBOAT_ROOT/blob
        - dd if=/dev/zero of=$TUGBOAT_ROOT/blob bs=1M count=51200 status=progress
