services:
  node:
    image: tugboatqa/node:12
    default: true
    commands:
      init:
        - apt-get update
        - apt-get install --yes jq
        - wget --quiet https://dashboard.tugboat.qa/cli/linux/tugboat.tar.gz
        - tar -xzf tugboat.tar.gz
        - mv tugboat /usr/local/bin
      build:
        - 'curl --silent
             -H "Authorization: Token $TUGBOAT_TOKEN"
             https://api.tugboat.qa/v3/previews/$TUGBOAT_PREVIEW_ID
             | jq .provider_ref.labels'
