services:
  one:
    image: tugboatqa/debian
    default: true
    commands:
      build:
        - date
        - |
          i=0
          while [ $i -lt 60 ]; do
            sleep 1
            i=$((i + 1))
            echo $((60-i))
          done
        - exit 1
