services:
  lighthouse:
    # We need to use Alpine because Chromium doesn't work properly on Debian.
    # See https://github.com/GoogleChrome/lighthouse/issues/7246
    image: 'tugboatqa/alpine:3.9'
    checkout: true
    expose: 9001
    commands:
      init:
        - apk update
        - apk add runit nodejs-current nodejs-current-npm curl chromium sqlite
        - npm install -g @lhci/cli@0.4.x
        - npm install --prefix=${TUGBOAT_ROOT}/tests/lighthouse-server
        - mkdir -p /etc/service/lighthouse-server
        - echo '#!/bin/sh' > /etc/service/lighthouse-server/run
        - echo "node ${TUGBOAT_ROOT}/tests/lighthouse-server" >> /etc/service/lighthouse-server/run
        - chmod +x /etc/service/lighthouse-server/run
        - sleep 5
        - 'curl http://localhost:9001/v1/projects
            --header "Content-Type: application/json"
            --request POST
            --data "{
              \"externalUrl\": \"https://github.com/${TUGBOAT_GITHUB_OWNER}/${TUGBOAT_GITHUB_REPO}\",
              \"name\": \"${TUGBOAT_REPO}\",
              \"baseBranch\": \"main\"
            }"'
#        - 'npm install --prefix=${TUGBOAT_ROOT}/tests/lighthouse'
#        - 'mkdir -p /etc/service/node'
#        - 'echo ''#!/bin/sh'' > /etc/service/node/run'
#        - 'echo "node ${TUGBOAT_ROOT}/tests/lighthouse" >> /etc/service/node/run'
#        - 'chmod +x /etc/service/node/run'
#      build:
#        - 'tests/lighthouse/test.sh || true'
