services:
  php:
    image: tugboatqa/php:8.4-apache
    default: true
    depends:
      - mariadb1
      - mariadb2
    commands:
      build:
        - mysql -e "SHOW TABLES;" -h mariadb2 -utugboat -ptugboat tugboat
        - mysql -e "SHOW TABLES;" -h mariadb1 -utugboat -ptugboat tugboat
  mariadb1:
    image: tugboatqa/mariadb:11.3
  mariadb2:
    image: tugboatqa/mariadb:11.4
