services:
  one:
    image: tugboatqa/debian
    default: true
    commands:
      build:
        - date
        - sleep 10
      online: |
        set -x
        hostname
        false
  two:
    image: tugboatqa/debian
    checkout: true
    commands:
      build:
        - date
      online: |
        set -x
        hostname
        true
      ready: test ! -f /var/lib/tugboat/.tugboat/config.yml || sleep 30
  three:
    image: tugboatqa/debian
    commands:
      build:
        - date
        - sleep 20
      online:
        - hostname && false
  four:
    image: tugboatqa/debian
    commands:
      build:
        - date
        - sleep 25
      online:
        - hostname && true
