services:
  apache:
    image: tugboatqa/httpd
    subpath: true
    commands:
      init:
        - echo "********** INIT **********"
        - apt-get update
        - apt-get install bsd-mailx
        - rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
        - ln -snf "${TUGBOAT_ROOT}/html" "${DOCROOT}"
      update:
        - echo "********** UPDATE **********"
      build:
        - echo "********** BUILD **********"
        - cat .tugboat/tugboat.txt | mail -s "[1] Tugboat Preview ${TUGBOAT_PREVIEW_ID}" tugboat@example.com
        - cat .tugboat/tugboat.txt | mail -s "[2] Tugboat Preview ${TUGBOAT_PREVIEW_ID}" tugboat@example.com
        - cat .tugboat/tugboat.txt
        - sed
          -e "s@style.css\"@$TUGBOAT_SERVICE_URL_PATH/&@"
          -e "s@logo.svg\"@$TUGBOAT_SERVICE_URL_PATH/&@"
          -i ${DOCROOT}/index.html