services:
  lighthouse:
    # We need to use Alpine because Chromium doesn't work properly on Debian.
    # See https://github.com/GoogleChrome/lighthouse/issues/7246
    image: 'tugboatqa/alpine:3.9'
    checkout: true
    expose: 9001
    commands:
      init:
        - apk update
        - apk add runit nodejs-current nodejs-current-npm curl chromium sqlite jq
        - npm install -g @lhci/cli@0.4.x
        - npm install --prefix=${TUGBOAT_ROOT}/tests/lighthouse-server
        - mkdir -p /etc/service/lighthouse-server
        - echo '#!/bin/sh' > /etc/service/lighthouse-server/run
        - echo "node ${TUGBOAT_ROOT}/tests/lighthouse-server" >> /etc/service/lighthouse-server/run
        - chmod +x /etc/service/lighthouse-server/run
        - sleep 5
        # Create the lighthouse project using the API, and save the resulting
        # json in a file. This file has the token, so we can then use that token
        # in build.
        - 'curl http://localhost:9001/v1/projects
            --header "Content-Type: application/json"
            --request POST
            --data "{
              \"externalUrl\": \"https://github.com/${TUGBOAT_GITHUB_OWNER}/${TUGBOAT_GITHUB_REPO}\",
              \"name\": \"${TUGBOAT_REPO}\",
              \"baseBranch\": \"main\"
            }" > lighthouse-project.json'
      build:
        # Collect a report… just for lullabot.com right now to prototype this.
        - lhci collect
            --url="https://www.lullabot.com"
            --settings.chromeFlags="--disable-gpu --no-sandbox"
        # Store the report, reading in the token from the project json file.
        - lhci upload
            --target=lhci
            --serverBaseUrl=http://localhost:9001
            --token=`cat lighthouse-project.json | jq -r '.token'`
