services:
  one:
    image: tugboatqa/alpine
    default: true
    depends:
      - two
    commands:
      build:
        - echo "$(hostname) start $(date)"
        - sleep 15
        - echo "$(hostname) end $(date)"
      online:
        - echo "$(hostname) start $(date)"
        - sleep 15
        - echo "$(hostname) end $(date)"
        - exit 23
  two:
    image: tugboatqa/alpine
    commands:
      build:
        - echo "$(hostname) start $(date)"
        - sleep 15
        - echo "$(hostname) end $(date)"
      online:
        - echo "$(hostname) start $(date)"
        - sleep 15
        - echo "$(hostname) end $(date)"
  three:
    image: tugboatqa/alpine
    depends:
      - two
    commands:
      build:
        - echo "$(hostname) start $(date)"
        - sleep 15
        - echo "$(hostname) end $(date)"
      online:
        - echo "$(hostname) start $(date)"
        - sleep 20
        - echo "$(hostname) end $(date)"
        - false
  four:
    image: tugboatqa/alpine
    depends:
      - one
    commands:
      build:
        - echo "$(hostname) start $(date)"
        - sleep 15
        - echo "$(hostname) end $(date)"
      online:
        - echo "$(hostname) start $(date)"
        - sleep 10
        - echo "$(hostname) end $(date)"
