services:
  lighthouse:
    image: 'tugboatqa/alpine:3.9'
    checkout: true
    expose: 3000
    commands:
      init:
        - apk update
        - apk add runit nodejs-current nodejs-current-npm curl chromium sqlite
        - npm install -g @lhci/cli@0.4.x
        - npm install --prefix=${TUGBOAT_ROOT}/tests/lighthouse-server
        - mkdir -p /etc/service/lighthouse-server
        - echo '#!/bin/sh' > /etc/service/lighthouse-server/run
        - echo "node ${TUGBOAT_ROOT}/tests/lighthouse-server" >> /etc/service/lighthouse-server/run
        - chmod +x /etc/service/lighthouse-server/run
#        - 'npm install --prefix=${TUGBOAT_ROOT}/tests/lighthouse'
#        - 'mkdir -p /etc/service/node'
#        - 'echo ''#!/bin/sh'' > /etc/service/node/run'
#        - 'echo "node ${TUGBOAT_ROOT}/tests/lighthouse" >> /etc/service/node/run'
#        - 'chmod +x /etc/service/node/run'
#      build:
#        - 'tests/lighthouse/test.sh || true'
