services:
  proxy:
    image: tugboatqa/httpd
    default: true
    aliases:
      - cms
      - web
    commands:
      init:
        - printf "\nInclude $TUGBOAT_ROOT/.tugboat/httpd.conf\n" >> /usr/local/apache2/conf/httpd.conf
      build:
        - echo "$TUGBOAT_PREVIEW_NAME"
            | awk -f .tugboat/qa-subdomain.awk
            > $TUGBOAT_ROOT/qa_subdomain.conf
  php:
    image: tugboatqa/php:7-apache
    commands:
      build:
        - mkdir -p $DOCROOT
        - echo '<pre><?php print_r($_SERVER); ?></pre>' > $DOCROOT/index.php
