services:
  one:
    image: tugboatqa/debian
    default: true
    subpath: true
    domain: tugboat.ibm.com
    commands:
      build:
        - date
        - sleep 10
  two:
    image: tugboatqa/debian
    commands:
      build:
        - date
        - sleep 15
  three:
    image: tugboatqa/debian
    commands:
      build:
        - date
        - sleep 20
  four:
    image: tugboatqa/debian
    commands:
      build:
        - date
        - sleep 25
