on:
  workflow_dispatch:
  schedule:
    - cron: '21 0 * * *'
jobs:
  tugboat_rebuild_base_previews:
    name: Rebuild Tugboat Base Previews
    env:
      TUGBOAT_REPO: 5ec2e1c6e7a500aa10c330f9
    runs-on: ubuntu-latest
    container:
      image: tugboatqa/cli
      env:
        TUGBOAT_API_TOKEN: ${{ secrets.TUGBOAT_API_TOKEN }}
    steps:
      - name: Find Base Previews
        id: find_base_previews
        run: |
          # Create a space-delimited list of all base previews
          base_previews=$(tugboat ls previews repo=${{ env.TUGBOAT_REPO }} -j | jq -r '[.[] | select(.anchor == true) | .id] | join(" ")')
          echo "::set-output name=base_previews::${base_previews}"
      - name: Rebuild Base Previews
        id: rebuild_base_previews
        if: ${{ steps.find_base_previews.outputs.base_previews }}
        run: |
          for x in ${{ steps.find_base_previews.outputs.base_previews }}; do
            tugboat -q rebuild $x force children
          done
