on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  tugboat_create_preview:
    runs-on: ubuntu-latest
    name: Create a Tugboat Preview
    steps:
      - name: Create Tugboat Preview
        id: tugboat_pr_preview
        run: |
          curl -H "Authorization: Bearer ${{ secrets.TUGBOAT_API_TOKEN }}" \
               -H "Content-Type: application/json" \
               -X POST \
               -d '{ "repo": "5ec2e1c6e7a500aa10c330f9", "ref": "pr${{ github.event.number }}", "name": "GHA ${{ github.event.title }}" }' \
               https://api.tugboat.qa/v3/previews
      - name: Create comment using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{"body": "A comment from **${{ github.workflow }}**."}'
