on:
  pull_request:
    types:
      - ready_for_review
      - review_requested

jobs:
  tugboat_create_preview:
    runs-on: ubuntu-latest
    name: Create a Tugboat Preview
    env:
      TUGBOAT_REPO: 5ec2e1c6e7a500aa10c330f9
    steps:
      - name: Create Tugboat Preview
        id: tugboat_pr_preview
        run: |
          curl -H "Authorization: Bearer ${{ secrets.TUGBOAT_API_TOKEN }}" \
               -H "Content-Type: application/json" \
               -X POST \
               -d '{ "repo": "${{ env.TUGBOAT_REPO }}", "ref": "${{ github.event.pull_request.head.ref }}", "name": "GHA ${{ github.event.pull_request.title }}", "type": "branch" }' \
               https://api.tugboat.qa/v3/previews
      - name: Create comment using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{"body": "A comment from **${{ github.workflow }}**."}'
